version: '3.4'

services:
   sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=ghp!@2023
      - ACCEPT_EULA=Y
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data   
    ports:
      - "1433:1433"  

   cadastrofuncionarios.api:
    image: ${DOCKER_REGISTRY-}cadastrofuncionariosapi
    build:
      context: .
      dockerfile: src/backend/CadastroFuncionarios.Api/Dockerfile
    depends_on:
     - sqldata
